name: fuwari_studio
description: FuwariStudio - cross-platform Markdown editor for Fuwari posts.
version: 1.0.2+6
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.4.10
  collection: ^1.18.0
  crop_your_image: ^2.0.0
  file_picker: ^8.0.6
  flutter_markdown: ^0.7.4
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  image: ^4.3.0
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  package_info_plus: ^8.0.3
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 700
